# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Marchine learning lab (You_Zhou Team)
description: >- # this means to ignore newlines until "baseurl:"
  Ji lin University_Marchine learning lab_You Zhou team. 
baseurl: "" # the subpath of the site
url: "https://sole12343.github.io" # the base hostname & protocol for the site
og_image: 


header:
  pages:
    - name: research content
      slug: /
    - name: team member
    - name: Whereabouts of members

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: m18640126583@163.com
      link: mailto:m18640126583@163.com
    - name: WeChat
      value: WhySoSerious12343
      link: "#"
  follow:
    - name: GitHub
      link: 
    - name: Weibo
      link: 
      name: WeChat
      link: 
    - name: RSS
      link: false

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
